create table hog (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        datetime TIMESTAMP NOT NULL,
        name varchar(100) NOT NULL,
        title  varchar(255) NOT NULL,
        category  varchar(100) NOT NULL,
        author  varchar(100) NOT NULL,
        content varchar(500) NOT NULL,
        image varchar(500) NOT NULL);